name: Mobile CI with maven
'on':
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: 'Build, Test & Report'
    runs-on: macOS-11
    steps:
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.5.app
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
      - name: Set up node
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Set up appium
      - run: |
            npm install -g appium@v1.21.0
            appium -v
      - name: Install Carthage
        run: brew install Carthage
      - name: List the Simulators
        run: xcrun xctrace list devices
      - name: Build with Maven
        run: mvn clean test site -DsuiteFile=ios_mobile_regression.xml -DremoteExecution=true
