name: Mobile CI for Android
'on':
  #  push:
  #     branches:
  #       - development
  workflow_dispatch:
jobs:
  build:
    name: 'Android regression'
    runs-on: macOS-11
    strategy:
      matrix:
        api-level: [ 29 ] #Google api level for example [25,23,28]
        target: [ default ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm -v
          node -v
      - name: Setup appium
        run: |
          npm install -g appium@v1.20.2
          appium -v

      - name: Android Regression with Maven
        uses: reactivecircus/android-emulator-runner@v1 # install and create the Emulator
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: mvn clean test site -DsuiteFile=android_mobile_regression.xml -DremoteExecution=true