name: MAC - iOS Mobile CI
'on':
#  push:
  #     branches:
  #       - development
  workflow_dispatch:
jobs:
  build:
    name: 'iOS Regression'
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.5.app
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm -v
          node -v

      # Step that does that actual cache save and restore
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup appium
        run: |
          npm install -g appium@v1.20.2
          npm install appium-doctor -g
          appium -v
          appium-doctor --ios
      #          appium &>/dev/null &
      - name: List the Simulators
        run: |
          xcrun simctl erase all
          xcrun xctrace list devices

      - name: iOS Regression with Maven
        run: mvn clean test site -DsuiteFile=ios_mobile_regression.xml -DremoteExecution=true
