name: MAC - Android Mobile CI
'on':
  push:
  #     branches:
  #       - development
  workflow_dispatch:
jobs:
  build:
    name: 'MacOS Android regression'
    runs-on: macOs-11
    strategy:
      matrix:
        api-level: [ 29 ] #Google api level for example [25,23,28]
        target: [ default ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm -v
          node -v
      - name: Setup appium
        run: |
          npm install -g appium@v1.20.2
          npm install appium-doctor -g
          appium -v
          appium-doctor --android

      - name: Copy  gradle properties file
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}


      # Step that does that actual cache save and restore
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure machine
        run: |
          adb devices
          adb kill-server
          adb start-server
          export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
          touch ~/.android/repositories.cfg

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      # install and create the Emulator
      - name: Android Regression with Maven on Ubuntu machine
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -verbose -show-kernel
          disable-animations: true
          arch: x86_64
          profile: Nexus 6
          script: |
            ./gradlew connectedCheck --stacktrace
            adb devices
            mvn clean test site -X -DsuiteFile=android_mobile_regression.xml -DremoteExecution=true