name: Mobile CI with maven
'on':
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: 'Build, Test & Report'
    runs-on: macOS-11
    steps:
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.5.app
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
      #       - name: Cache Maven packages to speed up
      #           uses: actions/cache@v2
      #           with:
      #             path: ~/.m2
      #             key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #             restore-keys: ${{ runner.os }}-m2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install appium & npm
        run: |
          npm install -g appium@v1.21.0
          appium -v
          node -v
          npm -v
          mvn -v
          pwd
      - name: List the Simulators
        run: xcrun xctrace list devices
      - name: Run iOS Regression tests on Simulator
        run: mvn clean test site -DsuiteFile=ios_mobile_regression.xml -DremoteExecution=true
