name: Mobile CI with maven
'on':
  push:
  #     branches:
  #       - development
  workflow_dispatch:
jobs:
  build:
    name: 'Build, Test & Report'
    runs-on: macOS-11
    steps:
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.5.app
      - name: Checkout branch
        uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
      - name: Cache Maven packages to speed up
          uses: actions/cache@v2
          with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          run: |
            npm install -g appium@v1.21.0
            appium -v
      - name: List the Simulators
        run: xcrun xctrace list devices
#      - name: Build with Maven
#        run: mvn clean test site -DsuiteFile=ios_mobile_regression.xml -DremoteExecution=true

      # - name: Allure report generation
      #   run: 'mvn allure:report'
      # - name: Get Allure history
      #   uses: actions/checkout@v2
      #   if: always()
      #   continue-on-error: true
      #   with:
      #     ref: gh-pages
      #     path: gh-pages
      # - name: Allure Report action from marketplace
      #   uses: simple-elf/allure-report-action@master
      #   if: always()
      #   with:
      #     allure_results: target/allure-results
      #     allure_history: allure-history
      # - name: Deploy report to Github Pages
      #   if: always()
      #   uses: peaceiris/actions-gh-pages@v2
      #   env:
      #     PERSONAL_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      #     PUBLISH_BRANCH: gh-pages
      #     PUBLISH_DIR: allure-history
