name: MAC - Android Mobile CI
'on':
  push:
    #     branches:
    #      - development
  workflow_dispatch:
jobs:
  build:
    name: 'MAC Android regression'
    runs-on: macos-11
    strategy:
      matrix:
        api-level: [ 29 ] #Google api level for example [25,23,28]
        target: [ default ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm -v
          node -v
      - name: Setup appium
        run: |
          npm install -g appium@v1.21.0
          npm install appium-doctor -g
          appium -v
          appium-doctor --android
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
             ~/.android/avd/*
             ~/.android/adb*
          key: avd-${{ matrix.api-level }}

        # Step that does that actual cache save and restore
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
              ${{ runner.os }}-maven-
      - name: Configure machine
        run: |
          export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
          touch ~/.android/repositories.cfg
          brew install --cask android-sdk
          appium-doctor --android

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        env:
          ANDROID_SDK_ROOT: ${{ ANDROID_HOME }}
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -verbose -show-kernel
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."


        # install and create the Emulator
      - name: Android Regression with Maven on MAC machine
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -verbose -show-kernel
          disable-animations: true
          arch: x86_64
          profile: Nexus 6
          script: |
            adb devices
            mvn clean test site -X -DsuiteFile=android_mobile_regression.xml -DremoteExecution=true
      - name: Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3

