name: Mobile CI with maven
'on':
  push:
  #     branches:
  #       - development
  workflow_dispatch:
jobs:
  build:
    name: 'Build, Test & Report'
    runs-on: macOS-11
    steps:
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.5.app
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm -v
          node -v
      - name: Setup appium
        run: |
          npm install -g appium@v1.21.0
          appium -v
      - name: install carthage
        run: brew install carthage
      - name: List the Simulators
        run: xcrun xctrace list devices
          
      - name: Build with Maven
        run: mvn -f /appium-template-qa/pom.xml clean test site -DsuiteFile=ios_mobile_regression.xml -DremoteExecution=true
